### ISSUE TITLE
crypto configs

### ISSUE THREAD

**Issue by ITUnfallen** [SamLatsin/crypto-nodes#1]
Hi there. i dont know how to contact you
Have a question about crypto configs. Can you explain where to put it?
Thx

**Comment by SamLatsin** [comment]
Hi, you can place it anywhere and run nodes with config path parameter.
DASH example:
```
dashd -conf=/root/.dashcore/dash.conf
```
Etherium example:
```
geth --http --http.api personal,eth,net,web3 --config "/root/.etherium/config.toml" --cache 2048
```
Monero example:
```
monerod --detach --config-file=/root/.bitmonero/monerod.conf
monero-wallet-rpc --disable-rpc-login --config-file /root/.bitmonero/monero-wallet-rpc.conf
```
Bitcoin config default location:
```
/root/.bitcoin/bitcoin.conf
```
Zcash config default location:
```
/root/.zcash/zcash.conf
```

**Comment by ITUnfallen** [comment]
Thx for your answer. Sorry for an issue, i didn't find any contacts here to contact you directly.
Found and set.
Awesome repository. Almost all working without any issues. Only have issues with BE install (
